This file should run first to change the dataset from normal data into game difference data

In [9]:
%matplotlib inline
import pandas as pd
import numpy as np
df = pd.read_csv('NBAPlayer_dataset.csv')

In [10]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)

In [11]:
df.fillna(0, inplace=True)

In [12]:
df

,playDispNm,next_gmDays,pre_gmDays,gmTime,teamDayOff,playMin,playHeight,playWeight,playPTS,playAST,...,opptDiv_Atlantic,opptDiv_Central,opptDiv_Northwest,opptDiv_Pacific,opptDiv_Southeast,opptDiv_Southwest,age,Seats,Year_Open,pre_gm_miles
0,Omari Johnson,1,2,3,1,16,81,220,5,1,...,0,1,0,0,0,0,31,18119,2004,0.000000
1,Damion Lee,2,2,7,2,26,78,210,14,1,...,0,0,0,0,1,0,35,18118,1999,336.553712
2,Damion Lee,2,2,7,1,32,78,210,20,1,...,1,0,0,0,0,0,36,18118,1999,0.000000
3,Damion Lee,2,2,6,1,23,78,210,4,2,...,0,0,0,0,1,0,38,18118,1999,0.000000
4,Damion Lee,2,1,7,1,23,78,210,15,1,...,0,0,0,0,1,0,26,18118,1999,0.000000
5,Rodney Purvis,2,1,7,0,6,76,205,5,0,...,0,1,0,0,0,0,28,18846,2010,401.298369
6,Rodney Purvis,6,2,7,2,14,76,205,4,0,...,1,0,0,0,0,0,30,18846,2010,401.298369
7,Rodney Purvis,2,6,7,2,22,76,205,19,1,...,1,0,0,0,0,0,37,18846,2010,461.769235
8,Rodney Purvis,4,2,7,2,17,76,205,6,1,...,0,0,0,1,0,0,32,18846,2010,859.524967
9,Rodney Purvis,2,4,7,4,24,76,205,2,1,...,1,0,0,0,0,0,40,18846,2010,0.000000
10,Rodney Purvis,2,2,7,2,23,76,205,5,1,...,0,1,0,0,0,0,41,18846,2010,0.000000
11,Rodney Purvis,2,1,7,0,23,76,205,7,1,...,0,0,0,0,0,1,40,18846,2010,0.000000
12,Rodney Purvis,2,2,7,2,27,76,205,12,3,...,0,0,0,0,1,0,31,18846,2010,0.000000
13,Xavier Rathan-Mayes,1,2,8,2,26,76,208,8,1,...,0,0,1,0,0,0,31,18119,2004,682.509351
14,Jaylen Morris,2,2,7,2,12,77,185,2,0,...,0,0,0,1,0,0,39,18118,1999,401.298369
15,Jaylen Morris,2,2,3,1,25,77,185,7,2,...,0,0,0,1,0,0,33,18118,1999,401.298369
16,Shaquille Harrison,2,1,9,1,9,76,185,2,1,...,0,0,1,0,0,0,37,18055,1992,1845.386683
17,Shaquille Harrison,2,2,9,2,1,76,185,0,0,...,0,0,1,0,0,0,38,18055,1992,1845.386683
18,Shaquille Harrison,2,3,10,3,11,76,185,10,0,...,0,1,0,0,0,0,41,18055,1992,1845.386683
19,Shaquille Harrison,3,2,10,2,20,76,185,8,2,...,0,0,0,1,0,0,35,18055,1992,1463.894931
20,Shaquille Harrison,3,3,10,3,16,76,185,4,2,...,0,1,0,0,0,0,30,18055,1992,2299.716492
21,Shaquille Harrison,2,2,10,2,10,76,185,2,1,...,1,0,0,0,0,0,32,18055,1992,2081.816396
22,Shaquille Harrison,2,2,10,2,31,76,185,17,2,...,0,0,0,1,0,0,38,18055,1992,0.000000
23,Shaquille Harrison,3,2,10,2,23,76,185,10,1,...,0,0,0,1,0,0,41,18055,1992,2145.803200
24,Shaquille Harrison,2,3,10,3,30,76,185,13,5,...,0,0,0,0,0,1,38,18055,1992,7541.330921
25,Shaquille Harrison,2,2,9,1,28,76,185,4,6,...,0,0,0,1,0,0,30,18055,1992,885.356530
26,Walter Lemon,2,3,8,3,5,75,180,2,0,...,0,0,0,1,0,0,30,16867,1999,0.000000
27,Andrew White,1,3,7,3,19,78,210,4,0,...,0,0,0,1,0,0,28,18118,1999,336.553712
28,Andrew White,2,2,3,1,14,78,210,7,0,...,0,1,0,0,0,0,41,18118,1999,0.000000
29,Andrew White,2,2,7,2,20,78,210,9,0,...,0,0,1,0,0,0,32,18118,1999,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153984,A.J. Price,1,2,19,2,19,74,195,13,1,...,0,1,0,0,0,0,26,20917,1994,7814.205136
153985,A.J. Price,1,3,19,3,22,74,195,4,3,...,0,1,0,0,0,0,23,18165,1999,7966.472876
153986,A.J. Price,2,1,19,1,32,74,195,23,0,...,0,0,0,0,1,0,25,19600,1999,1023.685261
153987,A.J. Price,3,2,19,2,22,74,195,6,2,...,1,0,0,0,0,0,21,20478,1996,1015.349655
153988,A.J. Price,4,2,20,2,1,74,195,0,0,...,0,0,0,1,0,0,24,19596,1966,2512.589456
153989,A.J. Price,3,3,20,2,12,74,195,0,1,...,0,1,0,0,0,0,25,20562,1994,2157.039366
153990,A.J. Price,6,3,20,1,3,74,195,3,0,...,1,0,0,0,0,0,17,18624,1995,550.547091
153991,A.J. Price,1,6,20,2,8,74,195,2,2,...,1,0,0,0,0,0,28,17732,2012,190.573067
153992,A.J. Price,3,6,20,3,9,74,195,0,2,...,0,0,0,0,1,0,33,19600,1999,1087.372141
153993,A.J. Price,1,7,20,5,2,74,195,0,2,...,0,0,0,0,1,0,17,20356,1997,922.450194
153994,A.J. Price,5,4,20,2,2,74,195,0,0,...,0,0,0,0,0,1,18,16867,1999,966.217546
153995,A.J. Price,2,4,20,2,6,74,195,3,1,...,0,0,0,0,1,0,20,19077,2005,649.837621
153996,A.J. Price,1,3,20,3,1,74,195,0,0,...,0,0,0,1,0,0,20,19067,1999,2121.345118
153997,A.J. Price,2,5,20,2,2,74,195,2,0,...,0,0,0,0,0,1,17,18055,2003,1375.325106
153998,A.J. Price,7,2,20,2,8,74,195,4,1,...,0,0,1,0,0,0,26,19155,1999,879.793063
153999,A.J. Price,3,7,20,7,1,74,195,0,0,...,0,1,0,0,0,0,29,18165,1999,1001.935478
154000,A.J. Price,2,1,20,2,1,74,195,0,1,...,1,0,0,0,0,0,21,19812,1968,646.012158
154001,A.J. Price,2,1,19,1,18,74,195,9,4,...,0,0,0,0,1,0,16,20356,1997,205.569462
154002,A.J. Price,2,2,19,2,25,74,195,22,1,...,0,0,1,0,0,0,17,19911,1991,1847.541622
154003,A.J. Price,1,2,19,2,24,74,195,14,4,...,0,0,1,0,0,0,21,19155,1999,371.021360
154004,A.J. Price,3,4,19,4,17,74,195,7,2,...,0,0,0,0,1,0,28,19077,2005,1359.788239
154005,A.J. Price,2,3,19,3,21,74,195,6,2,...,0,0,0,1,0,0,28,18055,1992,1782.673409
154006,A.J. Price,6,6,19,2,8,74,195,0,0,...,0,0,0,0,1,0,26,18118,1999,1591.364528
154007,A.J. Price,3,6,19,2,3,74,195,0,0,...,0,0,1,0,0,0,23,19356,1990,907.229776
154008,A.J. Price,2,2,16,2,18,74,195,2,4,...,0,1,0,0,0,0,21,20491,2017,543.245334
154009,A.J. Price,4,1,19,1,11,74,195,4,1,...,0,1,0,0,0,0,30,17500,2018,252.257751
154010,A.J. Price,1,4,13,2,14,74,195,6,3,...,0,0,0,0,0,1,26,19200,2001,856.926415
154011,A.J. Price,3,1,21,1,10,74,195,2,0,...,0,0,0,0,0,1,19,19200,2001,0.000000
154012,A.J. Price,2,3,22,3,4,74,195,0,0,...,0,0,0,1,0,0,28,17500,2016,1439.908507
154013,A.J. Price,3,2,22,2,4,74,195,0,1,...,0,0,1,0,0,0,24,19441,1995,483.505692

In [13]:
select_num = list(df.drop(columns=['gmDayofyear','gmElapsed','pre_gm_miles','gmDayofweek','gmDay','teamDayOff','pre_gmDays','next_gmDays','playDispNm','teamConfIsEast','opptConfIsEast', 'teamRsltIsWin', 'opptRsltltIsWin', 'teamLocIsHome', 'opptLocIsHome', 'playPos_C', 'playPos_F', 'playPos_G', 'playPos_PF', 'playPos_PG', 'playPos_SF', 'playPos_SG', 'teamDiv_Atlantic', 'teamDiv_Central', 'teamDiv_Northwest', 'teamDiv_Pacific', 'teamDiv_Southeast', 'teamDiv_Southwest', 'opptDiv_Atlantic', 'opptDiv_Central', 'opptDiv_Northwest', 'opptDiv_Pacific', 'opptDiv_Southeast','opptDiv_Southwest']).columns.values.tolist())

In [14]:
df.shape

(154014, 86)

In [15]:
len(select_num)

52

write a for loop for every player with almost every cols

In [16]:
playerlist = list(df['playDispNm'].unique())

In [17]:
%%time
df_list=[]
df_final = pd.DataFrame()
for player in playerlist:
    df_diff = df[df['playDispNm'] == player][select_num].diff()
    df_diff = df_diff.add_suffix('_diff')
    df_new = df[df['playDispNm'] == player].join(df_diff, how='outer')
    df_list.append(df_new)

CPU times: user 13.9 s, sys: 145 ms, total: 14 s
Wall time: 14.1 s

And now, we could have the NBA Player per game data transformed into difference from last game which would be more useful to predict would player increase or decrease his play minute in next game

In [18]:
df_new_diff = pd.concat(df_list)

In [19]:
df_new_diff.describe(include='all')

,playDispNm,next_gmDays,pre_gmDays,gmTime,teamDayOff,playMin,playHeight,playWeight,playPTS,playAST,...,playBIs_month_start_diff,playBIs_quarter_end_diff,playBIs_quarter_start_diff,playBIs_year_end_diff,playBIs_year_start_diff,playBElapsed_diff,IsStarter_diff,age_diff,Seats_diff,Year_Open_diff
count,154014,154014.000000,154014.000000,154014.000000,154014.000000,154014.000000,154014.000000,154014.000000,154014.000000,154014.000000,...,153119.0,153119.000000,153119.0,153119.0,153119.0,1.531190e+05,153119.000000,153119.000000,153119.000000,153119.000000
unique,895,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Corey Brewer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,482,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,2.349851,2.390562,15.682535,2.076396,22.988676,79.011609,217.932941,9.855974,2.185892,...,0.0,0.000007,0.0,0.0,0.0,5.365615e+03,0.000300,0.017019,-0.065753,-0.006217
std,NaN,1.277117,1.296341,5.880749,1.049777,10.690116,3.431578,25.942307,7.932366,2.532465,...,0.0,0.004426,0.0,0.0,0.0,3.295159e+06,0.278099,5.665299,1046.396279,11.421597
min,NaN,0.000000,0.000000,1.000000,0.000000,0.000000,69.000000,149.000000,0.000000,0.000000,...,0.0,-1.000000,0.0,0.0,0.0,-4.782240e+08,-1.000000,-22.000000,-4050.000000,-52.000000
25%,NaN,2.000000,2.000000,9.000000,2.000000,15.000000,77.000000,200.000000,4.000000,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.000000e+00,0.000000,-4.000000,-13.000000,0.000000
50%,NaN,2.000000,2.000000,19.000000,2.000000,24.000000,79.000000,220.000000,8.000000,1.000000,...,0.0,0.000000,0.0,0.0,0.0,0.000000e+00,0.000000,0.000000,0.000000,0.000000
75%,NaN,3.000000,3.000000,20.000000,2.000000,31.000000,82.000000,237.000000,15.000000,3.000000,...,0.0,0.000000,0.0,0.0,0.0,0.000000e+00,0.000000,4.000000,7.000000,0.000000
max,NaN,9.000000,9.000000,22.000000,11.000000,60.000000,87.000000,290.000000,62.000000,25.000000,...,0.0,1.000000,0.0,0.0,0.0,4.782240e+08,1.000000,21.000000,4050.000000,52.000000

In [20]:
df_new_diff.shape

(154014, 138)

In [21]:
df_new_diff.drop(columns=select_num, inplace=True)

In [22]:
df_new_diff.fillna(0, inplace=True)

In [23]:
df_new_diff.to_csv('2012-18_playerBoxScore_diff.csv')